In [1]:
import numpy as np
import pandas as pd

In [2]:
w = np.transpose([-2, 1, 0])
#weight matrix

In [3]:
lam = 0.07
#regularization constant

In [4]:
y = np.transpose([1, 1, 0, 0])
#class labels

In [5]:
X = np.array([[0, 3, 1], [1, 3, 1], [0, 1, 1], [1, 1, 1]])
#sample points

In [6]:
diags = np.array([(X[0] @ w) * (1 - (X[0] @ w)), (X[1] @ w) * (1 - (X[1] @ w)), (X[2] @ w) * (1 - (X[2] @ w)), (X[3] @ w) * (1 - (X[3] @ w))])
omega = np.diag(diags)
#diagonal matrix omega

In [7]:
omega

array([[-6,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0, -2]])

In [8]:
diags

array([-6,  0,  0, -2])

In [16]:
s = np.array([X[0] @ w, X[1] @ w, X[2] @ w, X[3] @ w])
s
#initial s vector

array([ 3,  1,  1, -1])

In [11]:
import math
for i in range(len(s)):
    s[i] = 1/(1 + math.exp(-s[i]))

In [15]:
1/(1 + math.exp(-3))

0.9525741268224334

In [17]:
1/(1 + math.exp(-1))

0.7310585786300049

In [18]:
1/(1 + math.exp(1))

0.2689414213699951

In [21]:
s = [0.9525741268224334, 0.7310585786300049, 0.7310585786300049, 0.2689414213699951]

In [22]:
np.linalg.inv(2*lam + (np.transpose(X) @ omega @ X)) @ (-2*lam*w + (np.transpose(X) @ (y - s)))

array([-1.61462387e+15, -8.07311933e+14,  2.42193580e+15])

In [25]:
np.linalg.solve(2*lam + (np.transpose(X) @ omega @ X), -2*lam*w + (np.transpose(X) @ (y - s)))

array([  20.32453055, -222.43425949,  230.98642894])

In [24]:
i = 0
while i < 3:
    if (i != 0):
        s = np.array([1/(1+math.exp(np.matmul(X[0], w))), 1/(1+math.exp(np.matmul(X[1], w))), 1/(1+math.exp(np.matmul(X[2], w))), 1/(1+math.exp(np.matmul(X[3], w)))])
        print("S:")
        print(s)
        diags = np.array([s[0] * (1 - s[0]), s[1] * (1 - s[1]), s[2] * (1 - s[2]), s[3] * (1 - s[3])])
        omega = np.diag(diags)
        print("Omega: ")
        print(omega)
        e = np.linalg.lstsq(2*lam + (np.matmul(np.matmul(np.transpose(X), omega), X)), -2*lam*w - np.matmul(np.transpose(X), y) + np.matmul(np.transpose(X), s))[0]
    else:
        e = np.linalg.lstsq(2*lam + (np.matmul(np.matmul(np.transpose(X), omega), X)), -2*lam*w - np.matmul(np.transpose(X), y) + np.matmul(np.transpose(X), s))[0]
    print("E:")
    print(e)
    w = w + e
    print("W:")
    print(w)
    i += 1

E:
[-0.20185686  0.04840402 -0.11843656]
W:
[-2.20185686  1.04840402 -0.11843656]
S:
[0.0462308  0.30472057 0.28293132 0.78106601]
Omega: 
[[0.04409351 0.         0.         0.        ]
 [0.         0.21186594 0.         0.        ]
 [0.         0.         0.20288119 0.        ]
 [0.         0.         0.         0.1710019 ]]
E:
[ 7.05185265 -5.29635423  3.2902904 ]
W:
[ 4.84999579 -4.2479502   3.17185383]
S:
[0.99993035 0.99118111 0.74575455 0.02244691]
Omega: 
[[6.96424628e-05 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.74111949e-03 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.89604703e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.19430508e-02]]
E:
[-12.37695809  32.53661262 -27.39046113]
W:
[ -7.5269623   28.28866242 -24.21860729]


C:\Users\EndlessWormhole\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  del sys.path[0]
C:\Users\EndlessWormhole\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  # This is added back by InteractiveShellApp.init_path()
